services:
  - type: web
    name: buildlink-web
    env: node
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_DATABASE_URL
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
      - key: REACT_APP_FIREBASE_MEASUREMENT_ID
        sync: false


